name: Build (Push)

on:
  push:
    branches: [ main ]

permissions:
  contents: read  # mínimo necessário

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Verify Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      # Build núcleo (JAR)
      - name: Build and test core
        run: ./gradlew build test --stacktrace --no-daemon

      - name: Upload JAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chess-jar
          path: build/libs/*.jar
          retention-days: 14

      # Build Android (APK)
      - name: Build Android APK (Debug)
        run: ./gradlew :android:assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chess-apk
          path: android/build/outputs/apk/debug/android-debug.apk
          retention-days: 14